import esbuild from "esbuild";
import process from "process";
import fs from "fs";
import path from "path";
import builtins from "builtin-modules";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, visit the plugin's repository
*/
`;

const prod = process.argv[2] === "production";

// Where to deploy build artefacts for live testing. Set OBSIDIAN_VAULT_DIR
// to your vault root; the plugin directory is derived as
// <vault>/.obsidian/plugins/<id> using the id from manifest.json.
// Deploy is skipped if OBSIDIAN_VAULT_DIR is not set.
const manifest = JSON.parse(fs.readFileSync("manifest.json", "utf8"));
const VAULT_PLUGIN_DIR =
	process.env.OBSIDIAN_VAULT_DIR &&
	path.join(
		process.env.OBSIDIAN_VAULT_DIR,
		".obsidian",
		"plugins",
		manifest.id
	);

const STATIC_FILES = ["manifest.json", "styles.css"];

function deploy(files) {
	if (!VAULT_PLUGIN_DIR) {
		console.warn("[deploy] skipped: OBSIDIAN_VAULT_DIR not set");
		return;
	}
	try {
		fs.mkdirSync(VAULT_PLUGIN_DIR, { recursive: true });
		for (const f of files) {
			if (fs.existsSync(f)) fs.copyFileSync(f, path.join(VAULT_PLUGIN_DIR, f));
		}
		console.log(`[deploy] copied ${files.join(", ")} -> vault`);
	} catch (e) {
		console.warn(`[deploy] skipped: ${e.message}`);
	}
}

/** esbuild plugin: copy main.js (+ static files) to the vault after each build. */
const deployPlugin = {
	name: "deploy-to-vault",
	setup(build) {
		build.onEnd((result) => {
			if (result.errors.length > 0) return;
			deploy(["main.js", ...STATIC_FILES]);
		});
	},
};

const context = await esbuild.context({
	banner: { js: banner },
	entryPoints: ["src/main.ts"],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtins,
	],
	format: "cjs",
	target: "es2018",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: "main.js",
	minify: prod,
	plugins: [deployPlugin],
});

if (prod) {
	await context.rebuild();
	await context.dispose();
	process.exit(0);
} else {
	await context.watch();
	// styles.css / manifest.json aren't part of the JS bundle, so watch them
	// separately and redeploy on change.
	for (const f of STATIC_FILES) {
		fs.watchFile(f, { interval: 300 }, () => deploy([f]));
	}
	console.log("[watch] watching src + static files; deploying on change…");
}
